-- Seed data for SnapConnect
-- This file contains sample data for testing the friend management features

-- Note: This seed data is for development/testing purposes only
-- In production, user data will be created through the application signup flow

-- Insert some test profiles
-- Note: These IDs are UUIDs that would normally be generated by Supabase Auth
-- For testing, we'll use fixed UUIDs

-- Test User 1: Johnny (The Creator)
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '11111111-1111-1111-1111-111111111111',
    'authenticated',
    'authenticated',
    'johnny@snapconnect.com',
    '$2a$10$example_encrypted_password_hash',
    NOW(),
    NOW(),
    '',
    NOW(),
    '',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"name":"johnny_creator"}',
    FALSE,
    NOW(),
    NOW(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
) ON CONFLICT (id) DO NOTHING;

-- Test User 2: Timmy (The Consumer)  
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '22222222-2222-2222-2222-222222222222',
    'authenticated',
    'authenticated',
    'timmy@snapconnect.com',
    '$2a$10$example_encrypted_password_hash',
    NOW(),
    NOW(),
    '',
    NOW(),
    '',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"name":"timmy_student"}',
    FALSE,
    NOW(),
    NOW(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
) ON CONFLICT (id) DO NOTHING;

-- Test User 3: Sarah (Active Trader)
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '33333333-3333-3333-3333-333333333333',
    'authenticated',
    'authenticated',
    'sarah@snapconnect.com',
    '$2a$10$example_encrypted_password_hash',
    NOW(),
    NOW(),
    '',
    NOW(),
    '',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"name":"sarah_trader"}',
    FALSE,
    NOW(),
    NOW(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
) ON CONFLICT (id) DO NOTHING;

-- Insert corresponding profiles (these will be created by the trigger, but we'll add them manually for testing)
INSERT INTO public.profiles (id, username, score) VALUES 
    ('11111111-1111-1111-1111-111111111111', 'johnny_creator', 150),
    ('22222222-2222-2222-2222-222222222222', 'timmy_student', 85),
    ('33333333-3333-3333-3333-333333333333', 'sarah_trader', 220)
ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    score = EXCLUDED.score;

-- Insert some sample friendships
INSERT INTO public.friendships (user_id_1, user_id_2, status) VALUES 
    -- Johnny and Timmy are friends
    ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 'accepted'),
    -- Sarah sent a friend request to Johnny (pending)
    ('33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 'pending')
ON CONFLICT (user_id_1, user_id_2) DO NOTHING;

-- Add some additional test users for friend suggestions
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
) VALUES 
    ('00000000-0000-0000-0000-000000000000', '44444444-4444-4444-4444-444444444444', 'authenticated', 'authenticated', 'alex@snapconnect.com', '$2a$10$example', NOW(), '{"provider":"email"}', '{"name":"alex_analyst"}', NOW(), NOW()),
    ('00000000-0000-0000-0000-000000000000', '55555555-5555-5555-5555-555555555555', 'authenticated', 'authenticated', 'maria@snapconnect.com', '$2a$10$example', NOW(), '{"provider":"email"}', '{"name":"maria_investor"}', NOW(), NOW()),
    ('00000000-0000-0000-0000-000000000000', '66666666-6666-6666-6666-666666666666', 'authenticated', 'authenticated', 'david@snapconnect.com', '$2a$10$example', NOW(), '{"provider":"email"}', '{"name":"david_finance"}', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.profiles (id, username, score) VALUES 
    ('44444444-4444-4444-4444-444444444444', 'alex_analyst', 95),
    ('55555555-5555-5555-5555-555555555555', 'maria_investor', 180),
    ('66666666-6666-6666-6666-666666666666', 'david_finance', 120)
ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    score = EXCLUDED.score;

-- Add comments for documentation
COMMENT ON TABLE auth.users IS 'Test users for development - these would normally be created through app signup';
COMMENT ON TABLE public.profiles IS 'Test profiles corresponding to auth users';
COMMENT ON TABLE public.friendships IS 'Sample friendship data for testing friend management features'; 